import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import open from 'open';
import Logger from './logger.js';

const logger = Logger.getInstance();

export interface VideoMetadata {
  videoId: string;
  title: string;
  duration?: number;
  uploader?: string;
}

export async function organizeAndOpenFolder(videoId: string, baseOutputPath: string): Promise<void> {
  const outputDir = join(baseOutputPath, videoId);
  
  // Create directory if it doesn't exist
  mkdirSync(outputDir, { recursive: true });
  
  logger.info(`Created folder for video ID: ${videoId}`);
}

export function generateMetadataInfo(videoId: string, metadata: VideoMetadata): void {
  const outputDir = join('./output', videoId);
  const filePath = join(outputDir, 'metadata-info.md');
  
  const content = `# Video Metadata\n\n` +
    `**Video ID:** ${videoId}\n` +
    `**Title:** ${metadata.title || 'Unknown'}\n` +
    `**Duration:** ${metadata.duration ? `${Math.floor(metadata.duration / 60)}:${(metadata.duration % 60).toString().padStart(2, '0')}` : 'Unknown'}\n` +
    `**Uploader:** ${metadata.uploader || 'Unknown'}\n\n` +
    `---\n` +
    `Generated by YouTube Downloader & Transcriber CLI\n`;

  writeFileSync(filePath, content);
  logger.info(`Generated metadata-info.md for video: ${videoId}`);
}

export async function openFolder(videoId: string): Promise<void> {
  const folderPath = join('./output', videoId);
  
  try {
    await open(folderPath);
    logger.info(`Opened output folder: ${folderPath}`);
  } catch (error) {
    logger.warn(`Could not open folder automatically. Path: ${folderPath}`);
  }
}

export async function organizeAndOpenAllFolders(videoIds: string[]): Promise<void> {
  for (const videoId of videoIds) {
    await organizeAndOpenFolder(videoId, './output');
  }
  
  // Open the last folder or main output folder
  if (videoIds.length > 0) {
    await openFolder(videoIds[videoIds.length - 1]);
  } else {
    logger.warn('No video folders to open');
  }
}